Try a workaround for an SQLite index creation error
This is to avoid this error, which we assume is because the
scraperwiki module isn't creating the end_date column if it's
NULL in the first data to be inserted.

{
     "area": "pagal s\u0105ra\u0161\u0105",
     "area_id": null,
     "birth_date": "1951-08-30",
     "email": "Gediminas.Kirkilas@lrs.lt",
     "end_date": null,
     "faction": "Lietuvos socialdemokrat\u0173 partijos frakcija",
     "family_name": "Kirkilas",
     "given_name": "Gediminas",
     "id": "117",
     "image": "http://www3.lrs.lt/home/seimo_nariu_nuotraukos/2012/gediminas_kirkilas.jpg",
     "name": "Gediminas Kirkilas",
     "party": "Lietuvos socialdemokrat\u0173 partija",
     "phone": "(8 5) 2396609",
     "sort_name": "Kirkilas, Gediminas",
     "source": "http://www3.lrs.lt/pls/inter/w5_show?p_a=5&p_asm_id=117&p_k=1&p_kade_id=7&p_r=8801",
     "start_date": "2012-11-17",
     "term": "11",
     "website": null
 }
 Traceback (most recent call last):
   File "scraper.py", line 171, in <module>
     data=person_data
   File "/app/.heroku/src/scraperwiki/scraperwiki/sqlite.py", line 33, in save
     dt.create_index(unique_keys, table_name, unique = True, if_not_exists = True)
   File "/app/.heroku/python/lib/python2.7/site-packages/dumptruck/dumptruck.py", line 168, in create_index
     self.execute(sql % params, **kwargs)
   File "/app/.heroku/python/lib/python2.7/site-packages/dumptruck/dumptruck.py", line 136, in execute
     self.cursor.execute(sql, *args)
 sqlite3.OperationalError: table data has no column named end_date